builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  mode: append
dockers:
  - image_templates:
      - "ghcr.io/curioswitch/protog:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/curioswitch/protog:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: "ghcr.io/curioswitch/protog:latest"
    image_templates:
      - "ghcr.io/curioswitch/protog:{{ .Version }}-amd64"
      - "ghcr.io/curioswitch/protog:{{ .Version }}-arm64"
  - name_template: "ghcr.io/curioswitch/protog:{{ .Version }}"
    image_templates:
      - "ghcr.io/curioswitch/protog:{{ .Version }}-amd64"
      - "ghcr.io/curioswitch/protog:{{ .Version }}-arm64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
