name: "Continuous Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.4'
          cache: true
      - id: cachedir
        run: echo "::set-output name=cache-dir::$(go run mage.go cachedir)"
      - uses: "actions/cache@v3"
        with:
          path: ${{ steps.cachedir.outputs.cache-dir }}
          key: ${{ runner.os }}-${{ runner.arch }}
      - run: go run mage.go test
